name: 'git-clang-format lint'
author: 'Yuxuan Shui'
description: 'Github Action that check if code is formatted correctly using clang-format'
branding:
  icon: 'align-left'
  color: 'green'
inputs:
  base:
    description: 'The base commit to calculate diff against'
    required: false
    default: 'HEAD^'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}

